import React from 'react'
import Link from 'next/link'
export const metadata = {
  title: "About Liproshine Consultancy",
  description:
    "Web and Mobile development company. Generated by STZ Technologies Private Limited",
};

const TestPage = () => {
  return (
    <>
      <div>About Liproshine</div>
      <p>    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore saepe nulla porro dolore adipisci, commodi voluptate magnam possimus vero pariatur, sequi libero explicabo nam iure. Ea omnis, quae blanditiis, expedita tempora voluptates, doloremque corporis quibusdam consequuntur labore quis ipsum in totam magnam iste earum minus non velit exercitationem voluptas itaque doloribus quam hic error. Voluptates distinctio, porro esse soluta doloremque vel alias dolor dolore cumque eveniet, ratione sunt deleniti repellendus.      </p>
      <p>    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore saepe nulla porro dolore adipisci, commodi voluptate magnam possimus vero pariatur, sequi libero explicabo nam iure. Ea omnis, quae blanditiis, expedita tempora voluptates, doloremque corporis quibusdam consequuntur labore quis ipsum in totam magnam iste earum minus non velit exercitationem voluptas itaque doloribus quam hic error. Voluptates distinctio, porro esse soluta doloremque vel alias dolor dolore cumque eveniet, ratione sunt deleniti repellendus.      </p>
      <p>    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore saepe nulla porro dolore adipisci, commodi voluptate magnam possimus vero pariatur, sequi libero explicabo nam iure. Ea omnis, quae blanditiis, expedita tempora voluptates, doloremque corporis quibusdam consequuntur labore quis ipsum in totam magnam iste earum minus non velit exercitationem voluptas itaque doloribus quam hic error. Voluptates distinctio, porro esse soluta doloremque vel alias dolor dolore cumque eveniet, ratione sunt deleniti repellendus.      </p>
      <p>    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore saepe nulla porro dolore adipisci, commodi voluptate magnam possimus vero pariatur, sequi libero explicabo nam iure. Ea omnis, quae blanditiis, expedita tempora voluptates, doloremque corporis quibusdam consequuntur labore quis ipsum in totam magnam iste earum minus non velit exercitationem voluptas itaque doloribus quam hic error. Voluptates distinctio, porro esse soluta doloremque vel alias dolor dolore cumque eveniet, ratione sunt deleniti repellendus.      </p>
      <p>    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempore saepe nulla porro dolore adipisci, commodi voluptate magnam possimus vero pariatur, sequi libero explicabo nam iure. Ea omnis, quae blanditiis, expedita tempora voluptates, doloremque corporis quibusdam consequuntur labore quis ipsum in totam magnam iste earum minus non velit exercitationem voluptas itaque doloribus quam hic error. Voluptates distinctio, porro esse soluta doloremque vel alias dolor dolore cumque eveniet, ratione sunt deleniti repellendus.      </p>
      <p></p><br></br>

    </>
  );
}

export default TestPage;