import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link'
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Liproshine Consultancy",
  description: "Web and Mobile development company. Generated by STZ Technologies Private Limited",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        {/* Responsive Welcome Text */}
        <p className="text-3xl md:text-3xl lg:text-4xl hidden md:block text-center my-8">
          Welcome to Liproshine
        </p>

        {/* Header */}
        <Header />

        {/* Main Content with Responsive Padding */}
        <main className="container mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </main>

        {/* Footer Section */}
        <section name="footer" className="mt-12">
          <Footer />
        </section>
      </body>
    </html>
  );
}
