import React from 'react'

import Link from 'next/link'

const HomePage = () => {
  return (
    <>
      <div>HomePage</div>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
      <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex perspiciatis eveniet enim, dignissimos laboriosam magnam minus ea, accusamus nesciunt tempore eius sapiente ipsum iusto quas vel reiciendis nulla eos, in molestias commodi. Tempore commodi illo exercitationem totam placeat quia iure molestiae est possimus deleniti molestias, numquam tenetur, voluptate ratione. Odit voluptatem, tempore eligendi minima id quos accusamus. Aliquid tempore inventore tempora aperiam rerum vero ipsum quidem impedit, voluptatem itaque dicta debitis illum iure architecto quod! Laboriosam ab dicta iusto magnam?</p>
    </>
  );
}

export default HomePage