import React from 'react'
import Link from 'next/link'
export const metadata = {
  title: "About Liproshine Consultancy",
  description:
    "Web and Mobile development company. Generated by STZ Technologies Private Limited",
};

const Services = () => {
  return (
    <>
      <div>Services Of  Liproshine</div>
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus
        tenetur nemo sunt iusto est. Porro est, facere, molestiae earum placeat
        autem sunt assumenda, voluptatum veniam ad doloribus! Doloremque nisi
        hic et soluta reiciendis laboriosam alias, cupiditate quae dolorem
        debitis est quaerat dolores illum enim perferendis temporibus iure at
        architecto quod, nihil molestias incidunt. Animi eveniet mollitia quo,
        minus porro facilis necessitatibus blanditiis deleniti eum iste. Minus,
        eum facilis. Odit, ratione? Fuga doloribus incidunt distinctio dolorem
        soluta nesciunt corporis magnam laudantium pariatur delectus, voluptas
        molestiae voluptates consequuntur culpa modi. Error numquam quidem
        excepturi illum, inventore corporis quis consectetur quae quibusdam id?
      </p>      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus
        tenetur nemo sunt iusto est. Porro est, facere, molestiae earum placeat
        autem sunt assumenda, voluptatum veniam ad doloribus! Doloremque nisi
        hic et soluta reiciendis laboriosam alias, cupiditate quae dolorem
        debitis est quaerat dolores illum enim perferendis temporibus iure at
        architecto quod, nihil molestias incidunt. Animi eveniet mollitia quo,
        minus porro facilis necessitatibus blanditiis deleniti eum iste. Minus,
        eum facilis. Odit, ratione? Fuga doloribus incidunt distinctio dolorem
        soluta nesciunt corporis magnam laudantium pariatur delectus, voluptas
        molestiae voluptates consequuntur culpa modi. Error numquam quidem
        excepturi illum, inventore corporis quis consectetur quae quibusdam id?
      </p>


      <p></p><br></br>

    </>
  );
}

export default Services;